ipa_kifz: #namespace
    task_and_robot_environment_name: 'IPA_KIFZ_Viewplanning-v0'

    #dqn parameters
    policy: 'MlpPolicy'
    learning_rate: 0.0001
    buffer_size: 1000000
    learning_starts: 100 #50000
    batch_size: 16 #1
    tau: 1.0
    gamma: 0.99
    train_freq: 1 #4
    gradient_steps: -1
    n_episodes_rollout: -1
    target_update_interval: 1 #10000
    exploration_fraction: 0.2 #0.2
    exploration_initial_eps: 1.0
    exploration_final_eps: 0.05
    max_grad_norm: 10

    # training parameters
    total_timesteps: 20000 #
    num_envs: 1